name: Setup and Build React App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Verify Node.js and npm installation
        run: |
          node -v
          npm -v

      - name: Install Create React App
        run: npm install -g create-react-app

      - name: Create React App
        run: npx create-react-app my-project-name

      - name: Navigate to React App
        run: cd my-project-name

      - name: Install dependencies
        run: |
          cd my-project-name
          npm install

      - name: Build React App
        run: |
          cd my-project-name
          npm run build
